[package]
name = "vedit-debugger"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5"
thiserror = "2.0"
iced-x86 = "1.21"
nix = { version = "0.30", features = ["ptrace", "signal"] }
libc = "0.2"