[package]
name = "vedit-workspace"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
slab = "0.4"
tempfile = "3"
vedit-vs = { path = "../vedit-vs" }
vedit-make = { path = "../vedit-make" }